### ISSUE TITLE
machine learning algorithm research

### ISSUE THREAD

**Issue by kripatailor** [Allen-ISD-Computer-Science/REPO_NASA_MedicalDataSynthesis_2024#24]
relates to #6

**Comment by janadaouk** [comment]
Have some ideas, will collaborate with Sophie regarding what she found in order to choose the best fit for our project and the approach we will be taking.

**Comment by SophieH8** [comment]
Discussed machine learning algorithm with Jana. Developed a game plan and completed research on developing an algorithm with youtube videos.
