### ISSUE TITLE
finding data sets

### ISSUE THREAD

**Issue by kripatailor** [Allen-ISD-Computer-Science/REPO_NASA_MedicalDataSynthesis_2024#25]
relates to #1

**Comment by Zoe-yau** [comment]
Began Research. Work in Progress.

**Comment by Zoe-yau** [comment]
[Disease Data Sets](https://docs.google.com/document/d/1EXykE4HwHyv_-kMNWl5lRpi8GF2AVbbkh9mQlSsUcFI/edit?usp=sharing) Link to the found data sets!
