### ISSUE TITLE
Connecting different elements of the project

### ISSUE THREAD

**Issue by kripatailor** [Allen-ISD-Computer-Science/REPO_NASA_MedicalDataSynthesis_2024#26]
relates to #18

**Comment by SirromEloc** [comment]
Obtained Raspberry Pi and researched possible medical interfaces, waiting for confirmation on necessary data to collect based on the chosen database.

**Comment by SirromEloc** [comment]
Connected Raspberry Pi to the repository, and researched types of sensors for later possible use. [link to expanding sensor list](https://docs.google.com/document/d/1bev_pCtR3SgQm85wdtezXVZ-LTQ9o52xD8six02ah-k/edit?usp=sharing)
